library(shiny)
library(shinyBS)
library(shinydashboard)
library(DT)
library(dygraphs)
library(stringr)
library(Rssa)
library(parallel)
library(plotly)
library(readr)

source("src/remove_na_values.R")
source("src/remove_outliers.R")
source("src/denoise.R")
source("src/aggregation.R")
source("src/timeSliders.R")
source("src/visualization.R")
source("src/train_test_split.R")

source("src/Model/aggregate.thresholds.R")
source("src/Model/app_timeseries.R")
source("src/Model/dynamicThreshold.model.R")
source("src/Model/dynamicThreshold.smart.R")
source("src/Model/dynamicThreshold.smart_train.two_sides.R")
source("src/Model/findPeriod_ssa.R")
source("src/Model/find_Thresh.R")
source("src/Model/find_Thresh_set.R")
source("src/Model/plotfirstPeriods.R")
source("src/Model/plotThresholdsAnomalies.R")
source("src/Model/timeseries_prepare.R")
source("src/Model/find.anomalies.R")
source("src/Model/find.anomalies.two_sides.R")
source("src/Model/InitDT.R")
source("src/Model/DTModelTrain.R")
source("src/Model/DTModelApply.R")
source("src/Model/DTModelTune.R")
source("src/Model/anomalies.analysis.R")

source("src/prophet/prophet_model.R")

options(shiny.maxRequestSize=2048*1024^2, shiny.deprecation.messages=FALSE)